from torch import Tensor
import torch
from torch import nn
import torch.utils.checkpoint
import contextlib
import torchvision
from einops import rearrange
import math
from transformers import MT5ForConditionalGeneration, T5Tokenizer 
import warnings
from config import mt5_path
from pytorch_i3d.pytorch_i3d import InceptionI3d
from vid_extractors import ResNetFeatureExtractor, EfficientNetV2FeatureExtractor, ViTFeatureExtractor, MobileNetV3FeatureExtractor, i3d
from keypoints_extractor import UniSignGNNSkeletonExtractor
def _no_grad_trunc_normal_(tensor, mean, std, a, b):
    # Cut & paste from PyTorch official master until it's in a few official releases - RW
    # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1. + math.erf(x / math.sqrt(2.))) / 2.

    if (mean < a - 2 * std) or (mean > b + 2 * std):
        warnings.warn("mean is more than 2 std from [a, b] in nn.init.trunc_normal_. "
                      "The distribution of values may be incorrect.",
                      stacklevel=2)

    with torch.no_grad():
        # Values are generated by using a truncated uniform distribution and
        # then using the inverse CDF for the normal distribution.
        # Get upper and lower cdf values
        l = norm_cdf((a - mean) / std)
        u = norm_cdf((b - mean) / std)

        # Uniformly fill tensor with values from [l, u], then translate to
        # [2l-1, 2u-1].
        tensor.uniform_(2 * l - 1, 2 * u - 1)

        # Use inverse cdf transform for normal distribution to get truncated
        # standard normal
        tensor.erfinv_()

        # Transform to proper mean, std
        tensor.mul_(std * math.sqrt(2.))
        tensor.add_(mean)

        # Clamp to ensure it's in the proper range
        tensor.clamp_(min=a, max=b)
        return tensor


def trunc_normal_(tensor, mean=0., std=1., a=-2., b=2.):
    # type: (Tensor, float, float, float, float) -> Tensor
    r"""Fills the input Tensor with values drawn from a truncated
    normal distribution. The values are effectively drawn from the
    normal distribution :math:`\mathcal{N}(\text{mean}, \text{std}^2)`
    with values outside :math:`[a, b]` redrawn until they are within
    the bounds. The method used for generating the random values works
    best when :math:`a \leq \text{mean} \leq b`.
    Args:
        tensor: an n-dimensional `torch.Tensor`
        mean: the mean of the normal distribution
        std: the standard deviation of the normal distribution
        a: the minimum cutoff value
        b: the maximum cutoff value
    Examples:
        >>> w = torch.empty(3, 5)
        >>> nn.init.trunc_normal_(w)
    """
    return _no_grad_trunc_normal_(tensor, mean, std, a, b)


class AttentionPooling(nn.Module):
    def __init__(self, input_dim=1536, num_output_tokens=50, num_heads=8):
        super().__init__()
        self.num_output_tokens = num_output_tokens
        self.input_dim = input_dim

        # Learnable query tokens
        self.query_tokens = nn.Parameter(torch.randn(num_output_tokens, input_dim))

        # Multi-head attention: queries = learned tokens, keys/values = input sequence
        self.attn = nn.MultiheadAttention(embed_dim=input_dim, num_heads=num_heads, batch_first=True)

    def forward(self, x):
        # x shape: (batch_size, seq_len=256, input_dim=1536)

        batch_size = x.size(0)
        queries = self.query_tokens.unsqueeze(0).expand(batch_size, -1, -1)  # (batch, 50, 1536)

        # Q: learned tokens, K/V: the full sequence
        output, _ = self.attn(query=queries, key=x, value=x)

        # output shape: (batch_size, 50, 1536)
        return output


class Uni_Sign(nn.Module):
    def __init__(self, args):
        super(Uni_Sign, self).__init__()
        self.args = args
        
        if self.args.skeleton_support:

            skeleton_extractor = self.args.skeleton_extractor
            if skeleton_extractor == 'unisign':
                self.skeleton_extractor = UniSignGNNSkeletonExtractor(args)
    
        if self.args.rgb_support:
            vid_extractor = self.args.vid_extractor
            freeze = True if self.args.freeze_vision_encoder else False
            if vid_extractor == 'resnet':
                self.feature_extractor = ResNetFeatureExtractor(freeze_vision_encoder=freeze)
            elif vid_extractor == 'EfficientNetV2':
                self.feature_extractor = EfficientNetV2FeatureExtractor(freeze_vision_encoder=freeze)
            elif vid_extractor == 'vit': 
                self.feature_extractor = ViTFeatureExtractor(freeze_vision_encoder=freeze)
            elif vid_extractor == 'mobilenet':
                self.feature_extractor = MobileNetV3FeatureExtractor(freeze_vision_encoder=freeze)
            elif vid_extractor == 'i3d':
                self.feature_extractor = i3d(freeze_vision_encoder=freeze)
            self.fusion_layer=nn.Linear(2*768, 768)

        self.apply(self._init_weights)

        self.mt5_model = MT5ForConditionalGeneration.from_pretrained(mt5_path)

        self.mt5_tokenizer = T5Tokenizer.from_pretrained(mt5_path, legacy=False)
    
        
    def _init_weights(self, m):
        if isinstance(m, nn.Linear):
            trunc_normal_(m.weight, std=.02)
            if isinstance(m, nn.Linear) and m.bias is not None:
                nn.init.constant_(m.bias, 0)
        elif isinstance(m, nn.LayerNorm):
            nn.init.constant_(m.bias, 0)
            nn.init.constant_(m.weight, 1.0)

    def maybe_autocast(self, dtype=torch.float32):
        # if on cpu, don't use autocast
        # if on gpu, use autocast with dtype if provided, otherwise use torch.float16
        # enable_autocast = self.device != torch.device("cpu")
        enable_autocast = True

        if enable_autocast:
            return torch.cuda.amp.autocast(dtype=dtype)
        else:
            return contextlib.nullcontext()

    def forward(self, src_input, tgt_input):
        """ src_input : dict dict_keys([
        'body' tensor(1, 255, 9, 3) #second dimension is different between
        'attention_mask', tensor (1, 255)
        'name_batch', list (1)
        'src_length_batch', tensor(1)
        'left', 
        'right',
        'face_all'])
        tgt_input : dict dict_keys(['gt_sentence' list
        , 'gt_gloss' list
        ])
        """
        
        if self.args.rgb_support:
            frames_embed = self.feature_extractor(src_input['frames'])
            inputs_embeds = frames_embed            

        if self.args.skeleton_support:
            if self.args.vid_extractor == 'i3d':
                skeleton_embeds = self.skeleton_extractor(src_input, T_target = frames_embed.shape[1])
            else:
                skeleton_embeds = self.skeleton_extractor(src_input)
            inputs_embeds = skeleton_embeds
            # print("frames embed: ", frames_embed.shape)
            # print("skeelton_embped: ", skeleton_embeds.shape)
            if self.args.rgb_support:
                inputs_embeds = self.fusion_layer(torch.cat([skeleton_embeds, frames_embed], dim=-1))

        prefix_token = self.mt5_tokenizer(
                                [f"Translate sign language video to English: "] * len(tgt_input["gt_sentence"]),
                                padding="longest",
                                truncation=True,
                                return_tensors="pt",
                            ).to(inputs_embeds.device) # 'transformers.tokenization_utils_base.BatchEncoding'

        prefix_embeds = self.mt5_model.encoder.embed_tokens(prefix_token['input_ids']) # tensor(1, 8, 768)

        inputs_embeds = torch.cat([prefix_embeds, inputs_embeds], dim=1) #tensor(1, 233, 768)

        if self.args.rgb_support and self.args.vid_extractor == 'i3d':
            B = frames_embed.shape[0]
            src_input['attention_mask'] = torch.ones(B, frames_embed.shape[1], device=frames_embed.device, dtype=prefix_token['attention_mask'].dtype)
        attention_mask = torch.cat([prefix_token['attention_mask'],
                                    src_input['attention_mask']], dim=1) #tensor(1, 233)

        tgt_input_tokenizer = self.mt5_tokenizer(tgt_input['gt_sentence'], 
                                                return_tensors="pt", 
                                                padding=True,
                                                truncation=True,
                                                max_length=50) #'transformers.tokenization_utils_base.BatchEncoding'
            
        # print('type tgt_input_tokenizer input_ ids: ', type(tgt_input_tokenizer['inputs_ids']))

        labels = tgt_input_tokenizer['input_ids'] #tensor(1, 28)
        labels[labels == self.mt5_tokenizer.pad_token_id] = -100
        out = self.mt5_model(
            inputs_embeds=inputs_embeds,
            attention_mask=attention_mask,
            labels=labels.to(inputs_embeds.device),
            return_dict=True)

        label = labels.reshape(-1)
        out_logits = out['logits'] # tensor (1, 28, 250112) second dimension is changing

        # print(out_logits.shape)
        logits = out_logits.reshape(-1,out_logits.shape[-1]) # nans

        loss_fct = torch.nn.CrossEntropyLoss(label_smoothing=self.args.label_smoothing, ignore_index=-100)

        loss = loss_fct(logits, label.to(out_logits.device, non_blocking=True))

        stack_out = {
            # use for inference
            'inputs_embeds':inputs_embeds,
            'attention_mask':attention_mask,
            'loss':loss,
        }

        return stack_out
    
    @torch.no_grad()
    def generate(self,pre_compute_item,max_new_tokens,num_beams):
        inputs_embeds = pre_compute_item['inputs_embeds']
        attention_mask = pre_compute_item['attention_mask']
       
        out = self.mt5_model.generate(inputs_embeds = inputs_embeds,
                                attention_mask = attention_mask,
                                max_new_tokens=max_new_tokens,
                                num_beams = num_beams,
                            )

        return out

def get_requires_grad_dict(model):
    param_requires_grad = {name: True for name, param in model.named_parameters()}
    param_requires_grad_right = {}
    for key in param_requires_grad.keys():
        if 'left' in key:
            param_requires_grad_right[key.replace("left", 'right')] = param_requires_grad[key]
    param_requires_grad = {**param_requires_grad,
                           **param_requires_grad_right}
    params_to_update = {k: v for k, v in model.state_dict().items() if param_requires_grad.get(k, True)}

    return params_to_update

